allow_reconnect: true

player_elimination_delay: 180

aggressive_decay: true

auto_start_decay: true

# Set to true to not play the wither death sound on end
disable_default_end_sound: false

snowball_voting: true

# This wont affect anything if snowball voting is enabled
give_snowballs: true